const products = [
    {
        id: 1,
        product_image:'/Sites/Equitas/Images/cucumber.jpg',
        product_wt: 10,
        product_name: 'Cucumber',
        current_price: 499,
        original_price: 999,
        discount: 50,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'vegetables',
    },
    {
        id: 2,
        product_image:'/Sites/Equitas/Images/bottlegourd.jpg',
        product_wt: 10,
        product_name: 'Bottle Gourd',
        current_price: 299,
        original_price: 699,
        discount: 60,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'vegetables',
    },
    {
        id: 3,
        product_image:'/Sites/Equitas/Images/lady-finger.jpg',
        product_wt: 10,
        product_name: 'Lady Finger',
        current_price: 399,
        original_price: 799,
        discount: 50,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'vegetables',
    },
    {
        id: 4,
        product_image:'/Sites/Equitas/Images/tomato.jpg',
        product_wt: 10,
        product_name: 'Tomato',
        current_price: 699,
        original_price: 1899,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'fruits',
    },
    {
        id: 5,
        product_image:'/Sites/Equitas/Images/watermellon.jpg',
        product_wt: 10,
        product_name: 'Water Mellon',
        current_price: 999,
        original_price: 2399,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'fruits',
    },
    {
        id: 6,
        product_image:'/Sites/Equitas/Images/maize.png',
        product_wt: 10,
        product_name: 'Water Mellon',
        current_price: 999,
        original_price: 2399,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'grains',
    },
    {
        id: 7,
        product_image:'/Sites/Equitas/Images/wheat.jpeg',
        product_wt: 10,
        product_name: 'Wheat',
        current_price: 999,
        original_price: 1699,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'grains',
    },
    {
        id: 8,
        product_image:'/Sites/Equitas/Images/rice.jpeg',
        product_wt: 10,
        product_name: 'Rice',
        current_price: 999,
        original_price: 1999,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'grains',
    },

    {
        id: 9,
        product_image:'/Sites/Equitas/Images/mango.jpeg',
        product_wt: 10,
        product_name: 'Mango',
        current_price: 999,
        original_price: 2999,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'fruits',
    },
    {
        id: 10,
        product_image:'/Sites/Equitas/Images/apple.jpeg',
        product_wt: 10,
        product_name: 'Apple',
        current_price: 999,
        original_price: 3399,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'fruits',
    },
    {
        id: 11,
        product_image:'/Sites/Equitas/Images/banana.jpeg',
        product_wt: 10,
        product_name: 'Banana',
        current_price: 999,
        original_price: 2599,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'fruits',
    },
    {
        id: 12,
        product_image:'/Sites/Equitas/Images/cauliflower.jpeg',
        product_wt: 10,
        product_name: 'Cauli flower',
        current_price: 999,
        original_price: 1999,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'vegetables',
    },
    {
        id: 13,
        product_image:'/Sites/Equitas/Images/guava.jpeg',
        product_wt: 10,
        product_name: 'Guava',
        current_price: 999,
        original_price: 2699,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'fruits',
    },
    {
        id: 14,
        product_image:'/Sites/Equitas/Images/greenchilli.jpeg',
        product_wt: 10,
        product_name: 'Green Chilli',
        current_price: 999,
        original_price: 1799,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'vegetables',
    },
    {
        id: 15,
        product_image:'/Sites/Equitas/Images/bajra.jpg',
        product_wt: 10,
        product_name: 'Bajra',
        current_price: 999,
        original_price: 1999,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'grains',
    },
    {
        id: 14,
        product_image:'/Sites/Equitas/Images/jawaar.jpeg',
        product_wt: 10,
        product_name: 'Jawaar',
        current_price: 999,
        original_price: 1999,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
        category: 'grains',
    },
];