const products = [
    {
        id: 1,
        product_image:'/Sites/Equitas/Images/cucumber.jpg',
        product_wt: 10,
        product_name: 'Cucumber',
        current_price: 499,
        original_price: 999,
        discount: 50,
        return_time: 14,
        delivery_date: '23 August 2023',
    },
    {
        id: 2,
        product_image:'/Sites/Equitas/Images/bottlegourd.jpg',
        product_wt: 10,
        product_name: 'Bottle Gourd',
        current_price: 299,
        original_price: 699,
        discount: 60,
        return_time: 14,
        delivery_date: '23 August 2023',
    },
    {
        id: 3,
        product_image:'/Sites/Equitas/Images/lady-finger.jpg',
        product_wt: 10,
        product_name: 'Lady Finger',
        current_price: 399,
        original_price: 799,
        discount: 50,
        return_time: 14,
        delivery_date: '23 August 2023',
    },
    {
        id: 4,
        product_image:'/Sites/Equitas/Images/tomato.jpg',
        product_wt: 10,
        product_name: 'Tomato',
        current_price: 699,
        original_price: 1899,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
    },
    {
        id: 5,
        product_image:'/Sites/Equitas/Images/watermellon.jpg',
        product_wt: 10,
        product_name: 'Water Mellon',
        current_price: 999,
        original_price: 2399,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
    },
    {
        id: 6,
        product_image:'',
        product_wt: 10,
        product_name: 'Water Mellon',
        current_price: 999,
        original_price: 2399,
        discount: 70,
        return_time: 14,
        delivery_date: '23 August 2023',
    },
];